-- Motor: PostgreSQL
-- Esquema relacional basado en diagramaUML.md

CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR,
    apellido VARCHAR,
    email VARCHAR,
    password_hash VARCHAR,
    zona_horaria VARCHAR,
    fecha_registro TIMESTAMP WITHOUT TIME ZONE,
    activo BOOLEAN,
    "fechaCreacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fechaActualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    actualizadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE categoria (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR,
    siglas VARCHAR,
    descripcion VARCHAR,
    pais_origen VARCHAR,
    logo_url VARCHAR,
    activo BOOLEAN,
    "fechaCreacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fechaActualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    actualizadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE temporada (
    id_temporada BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria BIGINT NOT NULL REFERENCES categoria(id_categoria) ON DELETE CASCADE,
    anio INTEGER,
    nombre VARCHAR,
    fecha_inicio DATE,
    fecha_fin DATE,
    "fechaCreacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fechaActualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    actualizadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE evento (
    id_evento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_temporada BIGINT NOT NULL REFERENCES temporada(id_temporada) ON DELETE CASCADE,
    id_externo VARCHAR,
    nombre VARCHAR,
    nombre_corto VARCHAR,
    numero_fecha INTEGER,
    pais VARCHAR,
    ciudad VARCHAR,
    circuito VARCHAR,
    fecha_inicio TIMESTAMP WITHOUT TIME ZONE,
    fecha_fin TIMESTAMP WITHOUT TIME ZONE,
    estado VARCHAR,
    "fechaCreacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fechaActualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    actualizadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE sesion (
    id_sesion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento BIGINT NOT NULL REFERENCES evento(id_evento) ON DELETE CASCADE,
    id_externo VARCHAR,
    nombre VARCHAR,
    tipo VARCHAR,
    numero INTEGER,
    fecha_inicio TIMESTAMP WITHOUT TIME ZONE,
    fecha_fin TIMESTAMP WITHOUT TIME ZONE,
    vueltas_programadas INTEGER,
    distancia DECIMAL,
    estado VARCHAR,
    "fechaCreacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fechaActualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    actualizadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE etapa (
    id_etapa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento BIGINT NOT NULL REFERENCES evento(id_evento) ON DELETE CASCADE,
    id_externo VARCHAR,
    numero INTEGER,
    nombre VARCHAR,
    dia INTEGER,
    distancia DECIMAL,
    fecha_inicio TIMESTAMP WITHOUT TIME ZONE,
    fecha_fin TIMESTAMP WITHOUT TIME ZONE,
    estado VARCHAR,
    "fechaCreacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fechaActualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    actualizadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE piloto (
    id_piloto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_externo VARCHAR,
    nombre VARCHAR,
    apellido VARCHAR,
    fecha_nacimiento DATE,
    nacionalidad VARCHAR,
    pais VARCHAR,
    codigo_piloto VARCHAR,
    numero_actual INTEGER,
    foto_url VARCHAR,
    fecha_inicio_carrera DATE,
    fecha_fin_carrera DATE,
    "fechaCreacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fechaActualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    actualizadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE equipo (
    id_equipo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_externo VARCHAR,
    nombre VARCHAR,
    nombre_corto VARCHAR,
    nacionalidad VARCHAR,
    logo_url VARCHAR,
    fecha_fundacion DATE,
    sede VARCHAR,
    "fechaCreacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fechaActualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    actualizadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE equipo_x_piloto (
    id_equipo_piloto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_equipo BIGINT NOT NULL REFERENCES equipo(id_equipo) ON DELETE CASCADE,
    id_piloto BIGINT NOT NULL REFERENCES piloto(id_piloto) ON DELETE CASCADE,
    id_categoria BIGINT NOT NULL REFERENCES categoria(id_categoria) ON DELETE CASCADE,
    temporada INTEGER,
    numero INTEGER,
    nro_piloto INTEGER,
    rol VARCHAR,
    fecha_desde DATE,
    fecha_hasta DATE,
    "fechaCreacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fechaActualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    actualizadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE tripulacion (
    id_tripulacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_equipo BIGINT NOT NULL REFERENCES equipo(id_equipo) ON DELETE CASCADE,
    id_categoria BIGINT NOT NULL REFERENCES categoria(id_categoria) ON DELETE CASCADE,
    id_piloto BIGINT NOT NULL REFERENCES piloto(id_piloto) ON DELETE CASCADE,
    id_copiloto BIGINT NOT NULL REFERENCES piloto(id_piloto) ON DELETE CASCADE,
    temporada INTEGER,
    numero INTEGER,
    "fechaCreacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fechaActualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    actualizadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE resultado_sesion (
    id_resultado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion BIGINT NOT NULL REFERENCES sesion(id_sesion) ON DELETE CASCADE,
    id_piloto BIGINT NOT NULL REFERENCES piloto(id_piloto) ON DELETE CASCADE,
    id_equipo BIGINT NOT NULL REFERENCES equipo(id_equipo) ON DELETE CASCADE,
    posicion INTEGER,
    numero INTEGER,
    puntos DECIMAL,
    tiempo DECIMAL,
    diferencia DECIMAL,
    vueltas INTEGER,
    mejor_vuelta DECIMAL,
    estado VARCHAR,
    motivo_abandono VARCHAR,
    "fechaCreacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fechaActualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    actualizadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE resultado_etapa (
    id_resultado_etapa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_etapa BIGINT NOT NULL REFERENCES etapa(id_etapa) ON DELETE CASCADE,
    id_tripulacion BIGINT NOT NULL REFERENCES tripulacion(id_tripulacion) ON DELETE CASCADE,
    posicion INTEGER,
    tiempo DECIMAL,
    diferencia DECIMAL,
    puntos DECIMAL,
    estado VARCHAR,
    motivo_abandono VARCHAR,
    "fechaCreacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fechaActualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    actualizadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE palmares (
    id_palmares BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_piloto BIGINT NOT NULL REFERENCES piloto(id_piloto) ON DELETE CASCADE,
    id_categoria BIGINT NOT NULL REFERENCES categoria(id_categoria) ON DELETE CASCADE,
    carreras INTEGER,
    victorias INTEGER,
    podios INTEGER,
    poles INTEGER,
    campeonatos INTEGER,
    puntos_totales DECIMAL,
    abandonos INTEGER,
    "fechaCreacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fechaActualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    actualizadopor BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_temporada_categoria ON temporada(id_categoria);
CREATE INDEX idx_evento_temporada ON evento(id_temporada);
CREATE INDEX idx_sesion_evento ON sesion(id_evento);
CREATE INDEX idx_etapa_evento ON etapa(id_evento);
CREATE INDEX idx_equipo_x_piloto_equipo ON equipo_x_piloto(id_equipo);
CREATE INDEX idx_equipo_x_piloto_piloto ON equipo_x_piloto(id_piloto);
CREATE INDEX idx_equipo_x_piloto_categoria ON equipo_x_piloto(id_categoria);
CREATE INDEX idx_tripulacion_equipo ON tripulacion(id_equipo);
CREATE INDEX idx_tripulacion_categoria ON tripulacion(id_categoria);
CREATE INDEX idx_tripulacion_piloto ON tripulacion(id_piloto);
CREATE INDEX idx_tripulacion_copiloto ON tripulacion(id_copiloto);
CREATE INDEX idx_resultado_sesion_sesion ON resultado_sesion(id_sesion);
CREATE INDEX idx_resultado_sesion_piloto ON resultado_sesion(id_piloto);
CREATE INDEX idx_resultado_sesion_equipo ON resultado_sesion(id_equipo);
CREATE INDEX idx_resultado_etapa_etapa ON resultado_etapa(id_etapa);
CREATE INDEX idx_resultado_etapa_tripulacion ON resultado_etapa(id_tripulacion);
CREATE INDEX idx_palmares_piloto ON palmares(id_piloto);
CREATE INDEX idx_palmares_categoria ON palmares(id_categoria);

CREATE OR REPLACE FUNCTION actualizar_fecha_actualizacion()
RETURNS TRIGGER AS $$
BEGIN
    NEW."fechaActualizacion" = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_usuario_fecha_actualizacion
BEFORE UPDATE ON usuario
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_actualizacion();

CREATE TRIGGER trg_categoria_fecha_actualizacion
BEFORE UPDATE ON categoria
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_actualizacion();

CREATE TRIGGER trg_temporada_fecha_actualizacion
BEFORE UPDATE ON temporada
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_actualizacion();

CREATE TRIGGER trg_evento_fecha_actualizacion
BEFORE UPDATE ON evento
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_actualizacion();

CREATE TRIGGER trg_sesion_fecha_actualizacion
BEFORE UPDATE ON sesion
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_actualizacion();

CREATE TRIGGER trg_etapa_fecha_actualizacion
BEFORE UPDATE ON etapa
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_actualizacion();

CREATE TRIGGER trg_piloto_fecha_actualizacion
BEFORE UPDATE ON piloto
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_actualizacion();

CREATE TRIGGER trg_equipo_fecha_actualizacion
BEFORE UPDATE ON equipo
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_actualizacion();

CREATE TRIGGER trg_equipo_x_piloto_fecha_actualizacion
BEFORE UPDATE ON equipo_x_piloto
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_actualizacion();

CREATE TRIGGER trg_tripulacion_fecha_actualizacion
BEFORE UPDATE ON tripulacion
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_actualizacion();

CREATE TRIGGER trg_resultado_sesion_fecha_actualizacion
BEFORE UPDATE ON resultado_sesion
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_actualizacion();

CREATE TRIGGER trg_resultado_etapa_fecha_actualizacion
BEFORE UPDATE ON resultado_etapa
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_actualizacion();

CREATE TRIGGER trg_palmares_fecha_actualizacion
BEFORE UPDATE ON palmares
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_actualizacion();